name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            cmake \
            libffi-dev \
            libssl-dev

          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          cd TelloControl_python_apk_kit/tello_control
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tello-apk
          path: TelloControl_python_apk_kit/tello_control/bin/*.apk
